//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asptest001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURENTCY_MASTER
    {
        public string EXC_ALIAS { get; set; }
        public Nullable<double> EXC_NUM { get; set; }
        public string EXC_NAME { get; set; }
    }
}
