//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asptest001.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbtestEntities1 : DbContext
    {
        public dbtestEntities1()
            : base("name=dbtestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CURENTCY_MASTER> CURENTCY_MASTER { get; set; }
        public virtual DbSet<Employee_member> Employee_member { get; set; }
        public virtual DbSet<EXCHANGERATES> EXCHANGERATES { get; set; }
        public virtual DbSet<Seal_order> Seal_order { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TD_Tempolary_Factory> TD_Tempolary_Factory { get; set; }
        public virtual DbSet<TM_Countrys> TM_Countrys { get; set; }
        public virtual DbSet<TM_Factory> TM_Factory { get; set; }
        public virtual DbSet<VW_EXCHENGERATES> VW_EXCHENGERATES { get; set; }
    }
}
