//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asptest001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_member
    {
        public int Emp_inx { get; set; }
        public string Emp_code { get; set; }
        public string Emp_efname { get; set; }
        public string Emp_elname { get; set; }
        public string Emp_tfname { get; set; }
        public string Emp_tlname { get; set; }
        public string Emp_position { get; set; }
        public Nullable<System.DateTime> Emp_birth_date { get; set; }
        public Nullable<System.DateTime> Emp_start_date { get; set; }
        public Nullable<System.DateTime> Emp_stop_date { get; set; }
        public Nullable<System.DateTime> Emp_updated_date { get; set; }
        public Nullable<System.DateTime> Emp_created_date { get; set; }
        public string Emp_created_by { get; set; }
        public string Emp_updated_by { get; set; }
        public string Emp_status { get; set; }
        public string Emp_username { get; set; }
        public string Emp_password { get; set; }
    }
}
