//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asptest001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Countrys
    {
        public int inx { get; set; }
        public string nation_id { get; set; }
        public string country_id { get; set; }
        public string nation_name_th { get; set; }
        public string nation_name_en { get; set; }
        public string country_name_th { get; set; }
        public string country_name_en { get; set; }
        public string area_one { get; set; }
        public string area_two { get; set; }
        public string area_percent { get; set; }
        public string remarks { get; set; }
        public string color_tag { get; set; }
    }
}
