//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asptest001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Factory
    {
        public string fact_id { get; set; }
        public string fact_name { get; set; }
        public string fact_owner { get; set; }
        public string fact_use { get; set; }
        public string addess { get; set; }
        public string m { get; set; }
        public string s { get; set; }
        public string t { get; set; }
        public string b { get; set; }
        public string provinc { get; set; }
        public string city { get; set; }
        public string zib { get; set; }
        public string phone { get; set; }
        public string typ { get; set; }
        public string money { get; set; }
        public string mand { get; set; }
        public string power { get; set; }
        public string TSIC { get; set; }
        public string old_num { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
