//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asptest001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXCHENGERATES
    {
        public Nullable<System.DateTime> EXCHENGE_DATE { get; set; }
        public Nullable<double> CAD { get; set; }
        public Nullable<double> HKD { get; set; }
        public Nullable<double> ISK { get; set; }
        public Nullable<double> PHP { get; set; }
        public Nullable<double> DKK { get; set; }
        public Nullable<double> HUF { get; set; }
        public Nullable<double> CZK { get; set; }
        public Nullable<double> GBP { get; set; }
        public Nullable<double> RON { get; set; }
        public Nullable<double> SEK { get; set; }
        public Nullable<double> IDR { get; set; }
        public Nullable<double> INR { get; set; }
        public Nullable<double> BRL { get; set; }
        public Nullable<double> RUB { get; set; }
        public Nullable<double> HRK { get; set; }
        public Nullable<double> JPY { get; set; }
        public Nullable<double> THB { get; set; }
        public Nullable<double> CHF { get; set; }
        public Nullable<double> EUR { get; set; }
        public Nullable<double> MYR { get; set; }
        public Nullable<double> BGN { get; set; }
        public Nullable<double> TRY { get; set; }
        public Nullable<double> CNY { get; set; }
        public Nullable<double> NOK { get; set; }
        public Nullable<double> NZD { get; set; }
        public Nullable<double> ZAR { get; set; }
        public Nullable<double> USD { get; set; }
        public Nullable<double> MXN { get; set; }
        public Nullable<double> SGD { get; set; }
        public Nullable<double> AUD { get; set; }
        public Nullable<double> ILS { get; set; }
        public Nullable<double> KRW { get; set; }
        public Nullable<double> PLN { get; set; }
        public int INS { get; set; }
    }
}
